# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: 'storageAccountName'
  type: string
  default: iacsa
- name: 'resourceGroupName'
  type: string
  default: IAC-RG
- name: 'containerName'
  type: string
  default: dscscripts


trigger:
  branches:
    include:
    - master
    - dsc
  paths:
    include:
    - dscs/*


pool:
  vmImage: windows-latest

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: IAC-SC
    azurePowerShellVersion: LatestVersion
    ScriptType: InlineScript
    Inline: |
      $storageAccountName = '${{ parameters.storageAccountName }}'
      $resourceGroupName = '${{ parameters.resourceGroupName }}'
      $StorageAccount = Get-AzStorageAccount -Name $storageAccountName -ResourceGroupName $resourceGroupName
      $Container = $StorageAccount | Get-AzStorageContainer -name '${{ parameters.containerName }}'

      Install-Module xActiveDirectory -Confirm:$false -Force
      Install-Module xPendingReboot -Confirm:$false -Force
      Install-Module xNetworking -Confirm:$false -Force
      Install-Module xComputerManagement -Confirm:$false -Force

      foreach ($file in $(((Get-ChildItem dsc).Name) | Where {$_ -like "*.ps1"}).split(".")[0]) {
        # Creating the ZIP file for the DSC Configuration
        Publish-AzVMDscConfiguration "dscs/$file.ps1" -OutputArchivePath  "dscs/$file.zip" -force
        $dscZipFilePath = "dscs/$file.zip"

        # Upload single file
        $Container | Set-AzStorageBlobContent -File $dscZipFilePath -Force
      }