---
- name: Configure exchange servers
  hosts: exchanges
  gather_facts: no
  vars:
    admin_username: "{{ admin_username }}"
    admin_password: "{{ ansible_winrm_password }}"
    safe_mode_password: "{{ ansible_winrm_password }}"
    domain_names: "{{ domain_names }}"
    dc_ips: "{{ dc_ips }}"

  pre_tasks:
    - name: wait 30 seconds for connection
      wait_for_connection:
        timeout: 120
        
    - name: set name prefix fact
      set_fact:
        # this split gets the name prefix for the particular workstation, then take the
        # domain name and private ip address from the extra vars passed
        domain_name: "{{ domain_names[inventory_hostname.split(\"-ex\")[0]] }}"
        domain_ip: "{{ dc_ips[inventory_hostname.split(\"-ex\")[0]] }}"

  roles:
#    - setup_ssh
    - join_domain
    - setup_exchange