---
- name: Configure workstations
  hosts: workstations
  vars:
    admin_username: "{{ admin_username }}"
    admin_password: "{{ ansible_winrm_password }}"
    safe_mode_password: "{{ ansible_winrm_password }}"
    domain_name: "{{ domain_name }}"

  tasks:
    - name: Set DC as DNS
      win_dns_client:
        adapter_names: "*"
        ipv4_addresses: "{{ hostvars[groups['dcs'][0]].private_ipv4_addresses }}"

    - name: Join workstation to domain
      win_domain_membership:
        dns_domain_name: "{{ domain_name }}"
        hostname: "{{ ansible_env.COMPUTERNAME }}"
        domain_admin_user: "{{ admin_username }}@{{ domain_name }}"
        domain_admin_password: "{{ admin_password }}"
        state: domain
      register: domain_state

    - name: Reboot workstation if neccassary
      win_reboot: {}
      when: domain_state.reboot_required