---
# vars file for setup_exchange
iso_checksum: 403EFE9589709461FCC09B332894C4ED1F0D93414D9DBDCED1A0967727C47063
features:
  - NET-Framework-45-Features
  - RPC-over-HTTP-proxy
  - RSAT-Clustering
  - RSAT-Clustering-CmdInterface
  - RSAT-Clustering-Mgmt
  - RSAT-Clustering-PowerShell
  - Web-Mgmt-Console
  - WAS-Process-Model
  - Web-Asp-Net45
  - Web-Basic-Auth
  - Web-Client-Auth
  - Web-Digest-Auth
  - Web-Dir-Browsing
  - Web-Dyn-Compression
  - Web-Http-Errors
  - Web-Http-Logging
  - Web-Http-Redirect
  - Web-Http-Tracing
  - Web-ISAPI-Ext
  - Web-ISAPI-Filter
  - Web-Lgcy-Mgmt-Console
  - Web-Metabase
  - Web-Mgmt-Console
  - Web-Mgmt-Service
  - Web-Net-Ext45
  - Web-Request-Monitor
  - Web-Server
  - Web-Stat-Compression
  - Web-Static-Content
  - Web-Windows-Auth
  - Web-WMI
  - Windows-Identity-Foundation
  - RSAT-ADDS
  - Server-Media-Foundation